// <auto-generated />
namespace LibraryAutomationSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class libraryv4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(libraryv4));
        
        string IMigrationMetadata.Id
        {
            get { return "202003151058535_library-v4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
