// <auto-generated />
namespace LibraryAutomationSystem.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class libraryv8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(libraryv8));
        
        string IMigrationMetadata.Id
        {
            get { return "202003160405380_library-v8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
